
name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:

  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t dlaw1/portfolio .


      - name: Push image
        run: |
        docker login -u dlaw1 -p ${{secret.REGRISTRY_PASS}}
        docker push dlaw1/portfolio
          
